### ISSUE TITLE
continuous action space

### ISSUE THREAD

**Issue by xiaowenkaihun** [lweitkamp/option-critic-pytorch#10]
Does this code support the continuous action space environment?

**Comment by lweitkamp** [comment]
There is no support for continuous action spaces currently, but there is no reason why it wouldn't be possible to augment the code to work with continuous action spaces. Each option essentially works as a policy gradient so you would have to change the following lines
https://github.com/lweitkamp/option-critic-pytorch/blob/102436cadf11e491933034952d6137d3e8e6795f/option_critic.py#L143-L144
where num_actions should be the dimensionality of the mean and diagonal covariance. Also change 
https://github.com/lweitkamp/option-critic-pytorch/blob/102436cadf11e491933034952d6137d3e8e6795f/option_critic.py#L172
to be a Gaussian distribution.
