### ISSUE TITLE
Actor called with a single sample 1/batchsize proportion of the time.

### ISSUE THREAD

**Issue by jms44** [lweitkamp/option-critic-pytorch#12]
I believe, when the batch size is reached, the action policy/loss is only computed with a single sample instead of one of size batch_size. This looks to be a major difference from the original implementation unless I am understanding the code wrong.

**Comment by lweitkamp** [comment]
The actor is updated at every step, this is how it is intended to work - it learns on-line. The critic learns offline, and hence can sample batches from the dataset (you can ctrl+f "on-line" in the paper)
