### ISSUE TITLE
Biased gradients

### ISSUE THREAD

**Issue by manuel-delverme** [lweitkamp/option-critic-pytorch#4]
you need to re-evaluate the features/state after the optimization step
optim.step()
because that updates the feature layer hence the features themselves

**Comment by lweitkamp** [comment]
Hey @manuel-delverme. Do you mean moving lines [112-114](https://github.com/lweitkamp/option-critic-pytorch/blob/0c57da7686f8903ed2d8dded3fae832ee9defd1a/main.py#L112-L114)

```
state = option_critic.get_state(to_tensor(next_obs))
option_termination, greedy_option = option_critic.predict_option_termination(state, current_option)
```
following the optimisation step?

**Comment by lweitkamp** [comment]
Fixed as of the latest commit
