### ISSUE TITLE
Got an error of inplace operation while running the code

### ISSUE THREAD

**Issue by mw9385** [lweitkamp/option-critic-pytorch#5]
Hi, I got **inplace operation message** while running your code.  It seems to be caused by wrong detach in calculating the loss function.  I tried to find a similar issue but I could not find anything. Could you have a look at it?

```
Traceback (most recent call last):
  File "main.py", line 147, in <module>
    run(args)
  File "main.py", line 129, in run
    loss.backward()
  File "/home/mw/anaconda3/envs/HRL/lib/python3.6/site-packages/torch/_tensor.py", line 255, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/home/mw/anaconda3/envs/HRL/lib/python3.6/site-packages/torch/autograd/__init__.py", line 149, in backward
    allow_unreachable=True, accumulate_grad=True)  # allow_unreachable flag
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [32, 64]], which is output 0 of TBackward, is at version 2; expected version 1 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).
```

**Comment by lweitkamp** [comment]
Hey, thanks for the notice! I created the code mostly on pytorch 1.4, and it seems that they have made some fundamental changes when it comes to shared architecture training. I tried fixing the issue but I couldn't. For now I would recommend downgrading pytorch to run the code, or start semi from scratch and see when errors occur. 

I am thinking of porting this code to Jax in the meantime.

**Comment by mw9385** [comment]
Thanks for the response. I donwgraded the pytorch version to 1.4 and the error is gone. I will close this issue.
